dist: trusty
language: c
compiler:
  - gcc
script: make
python:
  - "3.4"
before_install:
  - wget -O indri-5.9.tar.gz https://sourceforge.net/projects/lemur/files/lemur/indri-5.9/indri-5.9.tar.gz/download
  - tar -xzf indri-5.9.tar.gz
  - (cd indri-5.9 && chmod +x configure && ./configure && make)
  - mv indri-5.9 /home/`whoami`/
  - sudo apt-get update -qq
  - sudo apt-get install -qq ctags bison flex
  - sudo apt-get install -qq python3-pip python3-dev
  - sudo apt-get install -qq libtokyocabinet-dev libbz2-dev libz-dev
install:
  - sudo pip3 install jieba
